apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: report-exporter
  name: report-exporter
  namespace: dcireport
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: port
      port: 9100
      protocol: TCP
  selector:
    k8s-app: report-exporter